# Generated by Django 2.1.7 on 2019-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafeTitles', models.CharField(max_length=100)),
                ('cafeCallNums', models.CharField(max_length=100)),
                ('cafeImgs', models.CharField(max_length=500)),
                ('cafeAddrs', models.CharField(max_length=100)),
            ],
        ),
    ]
