# Generated by Django 2.1.7 on 2019-04-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='microDustInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('측정시간', models.CharField(max_length=100)),
                ('종로', models.IntegerField()),
                ('중구', models.IntegerField()),
                ('용산', models.IntegerField()),
                ('성동', models.IntegerField()),
                ('광진', models.IntegerField()),
                ('동대문', models.IntegerField()),
                ('중랑', models.IntegerField()),
                ('성북', models.IntegerField()),
                ('강북', models.IntegerField()),
                ('도봉', models.IntegerField()),
                ('노원', models.IntegerField()),
                ('은평', models.IntegerField()),
                ('서대문', models.IntegerField()),
                ('마포', models.IntegerField()),
                ('양천', models.IntegerField()),
                ('강서', models.IntegerField()),
                ('구로', models.IntegerField()),
                ('금천', models.IntegerField()),
                ('영등포', models.IntegerField()),
                ('동작', models.IntegerField()),
                ('관악', models.IntegerField()),
                ('서초', models.IntegerField()),
                ('강남', models.IntegerField()),
                ('송파', models.IntegerField()),
                ('강동', models.IntegerField()),
            ],
        ),
    ]
